### ISSUE TITLE
在wxapp正式环境里面，总是提示undefined异常，请问这个是什么问题？

### ISSUE THREAD

**Issue by welinkiot** [geekshop/paho.mqtt.javascript#1]

**Comment by w3hacker** [comment]
我还没在正式环境测试, 可能是还有一些代码没兼容吧

**Comment by welinkiot** [comment]
好的，非常感谢你的回复。

测试情况，在iOS设备中，SSL连接是正常的，android设备中，小程序提示certificate unknown. 目前还在排查情况，后续有结果，邮件回复一下处理的结果。

Eric · 尚科 | 研发工程师 | (86)186 8247 5952
____________________
深圳市联络者科技有限公司
深圳市南山区留仙大道1183南山云谷(一期)综合楼7楼B7&C9
(0086)0755 2660 8130 | www.welink.io <http://www.welink.io/>

**Comment by w3hacker** [comment]
Bug & Tip
tip: content-type 默认为 'application/json'
bug: 开发者工具 0.10.102800 版本，header 的 content-type 设置异常；
tip: 客户端的 HTTPS TLS 版本为1.2，但 Android 的部分机型还未支持 TLS 1.2，所以请确保 HTTPS 服务器的 TLS 版本支持1.2及以下版本；
tip: 要注意 method 的 value 必须为大写（例如：GET）；
tip: url 中不能有端口；
tip: request 的默认超时时间和最大超时时间都是 60s
tip: request 的最大并发数是 5
tip: 网络请求的 referer 是不可以设置的，格式固定为 https://servicewechat.com/{appid}/{version}/page-frame.html，其中 {appid} 为小程序的 appid，{version} 为小程序的版本号，版本号为 0 表示为开发版。

**Comment by w3hacker** [comment]
https://mp.weixin.qq.com/debug/wxadoc/dev/api/network-request.html

**Comment by w3hacker** [comment]
@welinkiot 我已经在线上测试过android了，没问题，你那个问题应该是ssl证书的问题，我是从阿里云申请的免费证书，测试没问题。

**Comment by welinkiot** [comment]
非常感谢你的回复，我在好好检查一下是不是这个原因，谢谢了！

Eric · 尚科 | 研发工程师 | (86)186 8247 5952
____________________
深圳市联络者科技有限公司
深圳市南山区留仙大道1183南山云谷(一期)综合楼7楼A3
(0086)0755 2660 8130 | www.welink.io <http://www.welink.io/>
